
version: 2

sources:
  - name: attendances
    database: eoffice  
    schema: public  
    tables:
      - name: TimeRecordUser
      - name: UserMapper
      - name: attendance_excel
      - name: record_user
      - name: Attendance
